version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo:4.2.8
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  pisignage-server:
    image: pisignage/pisignage-server:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - media:/media
      - data:/data
    depends_on:
      - mongo

volumes:
  mongodb:
  mongodb_config:
  media:
  data:
